package com.slw.my_user.dao;

import com.slw.my_user.model.GoodsHistory;
import com.slw.my_user.model.GoodsHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    long countByExample(GoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int deleteByExample(GoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int insert(GoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int insertSelective(GoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    List<GoodsHistory> selectByExample(GoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    GoodsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsHistory record, @Param("example") GoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByExample(@Param("record") GoodsHistory record, @Param("example") GoodsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods_history
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByPrimaryKey(GoodsHistory record);
}