package com.slw.my_user.dao;

import com.slw.my_user.model.Goods;
import com.slw.my_user.model.GoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    long countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_goods
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    int updateByPrimaryKey(Goods record);
}