package com.slw.my_user.dao;

import com.slw.my_user.model.Relationship;
import com.slw.my_user.model.RelationshipExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    long countByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int deleteByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int insertSelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    List<Relationship> selectByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    Relationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int updateByExample(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int updateByPrimaryKeySelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    int updateByPrimaryKey(Relationship record);
}