package com.slw.my_user.dao;

import com.slw.my_user.model.User;
import com.slw.my_user.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    int updateByPrimaryKey(User record);
}