package com.slw.my_user.model;

import java.util.Date;

public class Relationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.id
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.relationship_type
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Integer relationshipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.person_one
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Integer personOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.person_two
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Integer personTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.create_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.expire_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.delete_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.valid
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.operator
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    private Integer operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.id
     *
     * @return the value of s_user.t_relationship.id
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.id
     *
     * @param id the value for s_user.t_relationship.id
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.relationship_type
     *
     * @return the value of s_user.t_relationship.relationship_type
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Integer getRelationshipType() {
        return relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.relationship_type
     *
     * @param relationshipType the value for s_user.t_relationship.relationship_type
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setRelationshipType(Integer relationshipType) {
        this.relationshipType = relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.person_one
     *
     * @return the value of s_user.t_relationship.person_one
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Integer getPersonOne() {
        return personOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.person_one
     *
     * @param personOne the value for s_user.t_relationship.person_one
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setPersonOne(Integer personOne) {
        this.personOne = personOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.person_two
     *
     * @return the value of s_user.t_relationship.person_two
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Integer getPersonTwo() {
        return personTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.person_two
     *
     * @param personTwo the value for s_user.t_relationship.person_two
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setPersonTwo(Integer personTwo) {
        this.personTwo = personTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.create_time
     *
     * @return the value of s_user.t_relationship.create_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.create_time
     *
     * @param createTime the value for s_user.t_relationship.create_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.expire_time
     *
     * @return the value of s_user.t_relationship.expire_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.expire_time
     *
     * @param expireTime the value for s_user.t_relationship.expire_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.delete_time
     *
     * @return the value of s_user.t_relationship.delete_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.delete_time
     *
     * @param deleteTime the value for s_user.t_relationship.delete_time
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.valid
     *
     * @return the value of s_user.t_relationship.valid
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.valid
     *
     * @param valid the value for s_user.t_relationship.valid
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.operator
     *
     * @return the value of s_user.t_relationship.operator
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.operator
     *
     * @param operator the value for s_user.t_relationship.operator
     *
     * @mbg.generated Sun May 17 20:53:52 CST 2020
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }
}