package com.slw.my_user.model;

public class Relationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.id
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.relationship_type
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer relationshipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.person_one
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer personOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.person_two
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer personTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.create_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.expire_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Long expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.delete_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Long deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.valid
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_relationship.operator
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    private Integer operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Relationship(Integer id, Integer relationshipType, Integer personOne, Integer personTwo, Long createTime, Long expireTime, Long deleteTime, Integer valid, Integer operator) {
        this.id = id;
        this.relationshipType = relationshipType;
        this.personOne = personOne;
        this.personTwo = personTwo;
        this.createTime = createTime;
        this.expireTime = expireTime;
        this.deleteTime = deleteTime;
        this.valid = valid;
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_relationship
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Relationship() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.id
     *
     * @return the value of s_user.t_relationship.id
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.id
     *
     * @param id the value for s_user.t_relationship.id
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.relationship_type
     *
     * @return the value of s_user.t_relationship.relationship_type
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getRelationshipType() {
        return relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.relationship_type
     *
     * @param relationshipType the value for s_user.t_relationship.relationship_type
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setRelationshipType(Integer relationshipType) {
        this.relationshipType = relationshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.person_one
     *
     * @return the value of s_user.t_relationship.person_one
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getPersonOne() {
        return personOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.person_one
     *
     * @param personOne the value for s_user.t_relationship.person_one
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setPersonOne(Integer personOne) {
        this.personOne = personOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.person_two
     *
     * @return the value of s_user.t_relationship.person_two
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getPersonTwo() {
        return personTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.person_two
     *
     * @param personTwo the value for s_user.t_relationship.person_two
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setPersonTwo(Integer personTwo) {
        this.personTwo = personTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.create_time
     *
     * @return the value of s_user.t_relationship.create_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.create_time
     *
     * @param createTime the value for s_user.t_relationship.create_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.expire_time
     *
     * @return the value of s_user.t_relationship.expire_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Long getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.expire_time
     *
     * @param expireTime the value for s_user.t_relationship.expire_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.delete_time
     *
     * @return the value of s_user.t_relationship.delete_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Long getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.delete_time
     *
     * @param deleteTime the value for s_user.t_relationship.delete_time
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setDeleteTime(Long deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.valid
     *
     * @return the value of s_user.t_relationship.valid
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.valid
     *
     * @param valid the value for s_user.t_relationship.valid
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_relationship.operator
     *
     * @return the value of s_user.t_relationship.operator
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_relationship.operator
     *
     * @param operator the value for s_user.t_relationship.operator
     *
     * @mbg.generated Tue Jun 09 13:48:15 CST 2020
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }
}