package com.slw.my_user.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_person.id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_person.name
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_person.phone
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_person.relationship_id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    private Integer[] relationshipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.t_person.valid
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public User(Integer id, String name, String phone, Integer[] relationshipId, Integer valid) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.relationshipId = relationshipId;
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user.t_person
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_person.id
     *
     * @return the value of s_user.t_person.id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_person.id
     *
     * @param id the value for s_user.t_person.id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_person.name
     *
     * @return the value of s_user.t_person.name
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_person.name
     *
     * @param name the value for s_user.t_person.name
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_person.phone
     *
     * @return the value of s_user.t_person.phone
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_person.phone
     *
     * @param phone the value for s_user.t_person.phone
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_person.relationship_id
     *
     * @return the value of s_user.t_person.relationship_id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public Integer[] getRelationshipId() {
        return relationshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_person.relationship_id
     *
     * @param relationshipId the value for s_user.t_person.relationship_id
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public void setRelationshipId(Integer[] relationshipId) {
        this.relationshipId = relationshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.t_person.valid
     *
     * @return the value of s_user.t_person.valid
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.t_person.valid
     *
     * @param valid the value for s_user.t_person.valid
     *
     * @mbg.generated Wed Jun 03 16:42:51 CST 2020
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}